clear_color: [0.08, 0.09, 0.12]
ambient: [0.08, 0.08, 0.08]
camera:
  position:
    - 3.72106051
    - 4.11571121
    - 6.77742958
  target:
    - 3.31039143
    - 3.69540238
    - 5.96829987
  fov: 45
lights:
  - type: point
    position:
      - -3
      - 5
      - -2
    color:
      - 1
      - 1
      - 1
    intensity: 1.20000005
objects:
  - name: sphere
    mesh: builtin:sphere
    transform:
      position:
        - -1.08997488
        - 1
        - 0
      rotation:
        - 0
        - -0
        - 0
      scale:
        - 1
        - 1
        - 1
    material:
      albedo: [0.75, 0.35, 0.25]
  - name: cube
    mesh: builtin:cube
    transform:
      position:
        - 1.39999998
        - 1.13199949
        - -0.400000006
      rotation:
        - 0
        - -0
        - 0
      scale:
        - 0.800000012
        - 0.800000012
        - 0.800000012
    material:
      albedo: [0.35, 0.55, 0.85]
  - name: plane
    mesh: builtin:plane
    transform:
      position:
        - 0
        - 0
        - 0
      rotation:
        - 0
        - -0
        - 0
      scale:
        - 10
        - 1
        - 10
    material:
      albedo: [0.55, 0.55, 0.55]